import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "en" | "hi";

const translations = {
  en: {
    home: "Home",
    chat: "Chat",
    symptoms: "Symptoms",
    profile: "Profile",
    dashboard: "Dashboard",
    welcome: "Welcome to Niramaya",
    welcomeSub: "Your personal health companion — track symptoms, chat with AI, and monitor your wellness journey.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    quickActions: "Quick Actions",
    checkSymptoms: "Check Symptoms",
    checkSymptomsSub: "Identify potential conditions based on your symptoms",
    chatDoctor: "Chat with AI Doctor",
    chatDoctorSub: "Get instant health guidance from our AI assistant",
    viewDashboard: "View Dashboard",
    viewDashboardSub: "Track your health metrics and analytics",
    healthTip: "Health Tip of the Day",
    healthTipText: "Stay hydrated! Drinking 8 glasses of water daily boosts your immune system and improves overall health.",
    recentActivity: "Recent Activity",
    noActivity: "No recent activity yet. Start by checking your symptoms!",
    typeMessage: "Type your message...",
    send: "Send",
    aiGreeting: "Hello! I'm your AI health assistant. How can I help you today?",
    selectSymptoms: "Select Your Symptoms",
    selectSymptomsSub: "Choose from the categories below to identify your symptoms",
    selectedSymptoms: "Selected Symptoms",
    analyzeSymptoms: "Analyze Symptoms",
    clearAll: "Clear All",
    noSymptomsSelected: "No symptoms selected yet",
    userProfile: "User Profile",
    personalInfo: "Personal Information",
    name: "Name",
    email: "Email",
    phone: "Phone",
    bloodType: "Blood Type",
    history: "Medical History",
    consultations: "Past Consultations",
    noHistory: "No consultation history yet",
    analyticsTitle: "Health Analytics Dashboard",
    analyticsSub: "Monitor your health trends and metrics",
    heartRate: "Heart Rate",
    bloodPressure: "Blood Pressure",
    sleepHours: "Sleep Hours",
    stepsToday: "Steps Today",
    weeklyTrend: "Weekly Health Trend",
    monthlyOverview: "Monthly Overview",
    general: "General",
    headNeck: "Head & Neck",
    chestLungs: "Chest & Lungs",
    abdomen: "Abdomen",
    musculoskeletal: "Musculoskeletal",
    skinHair: "Skin & Hair",
    mental: "Mental Health",
    other: "Other",
    settings: "Settings",
    notifications: "Notifications",
    help: "Help & Support",
    logout: "Log Out",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    symptomsSaved: "Symptoms saved to your health history!",
    symptomHistory: "Symptom History",
    symptomEntries: "Symptom entries",
    symptomCheck: "Symptom Check",
  },
  hi: {
    home: "होम",
    chat: "चैट",
    symptoms: "लक्षण",
    profile: "प्रोफ़ाइल",
    dashboard: "डैशबोर्ड",
    welcome: "हेल्थकेयर में आपका स्वागत है",
    welcomeSub: "आपका व्यक्तिगत स्वास्थ्य साथी — लक्षण ट्रैक करें, AI से बात करें और अपनी वेलनेस यात्रा की निगरानी करें।",
    getStarted: "शुरू करें",
    learnMore: "और जानें",
    quickActions: "त्वरित कार्रवाई",
    checkSymptoms: "लक्षण जांचें",
    checkSymptomsSub: "अपने लक्षणों के आधार पर संभावित स्थितियों की पहचान करें",
    chatDoctor: "AI डॉक्टर से बात करें",
    chatDoctorSub: "हमारे AI सहायक से तुरंत स्वास्थ्य मार्गदर्शन प्राप्त करें",
    viewDashboard: "डैशबोर्ड देखें",
    viewDashboardSub: "अपने स्वास्थ्य मेट्रिक्स और एनालिटिक्स ट्रैक करें",
    healthTip: "आज का स्वास्थ्य सुझाव",
    healthTipText: "हाइड्रेटेड रहें! रोजाना 8 गिलास पानी पीने से आपकी प्रतिरक्षा प्रणाली मजबूत होती है।",
    recentActivity: "हाल की गतिविधि",
    noActivity: "अभी तक कोई गतिविधि नहीं। अपने लक्षणों की जांच करके शुरू करें!",
    typeMessage: "अपना संदेश लिखें...",
    send: "भेजें",
    aiGreeting: "नमस्ते! मैं आपका AI स्वास्थ्य सहायक हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ?",
    selectSymptoms: "अपने लक्षण चुनें",
    selectSymptomsSub: "अपने लक्षणों की पहचान करने के लिए नीचे दी गई श्रेणियों से चुनें",
    selectedSymptoms: "चयनित लक्षण",
    analyzeSymptoms: "लक्षणों का विश्लेषण करें",
    clearAll: "सभी हटाएं",
    noSymptomsSelected: "अभी तक कोई लक्षण नहीं चुना गया",
    userProfile: "उपयोगकर्ता प्रोफ़ाइल",
    personalInfo: "व्यक्तिगत जानकारी",
    name: "नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    bloodType: "रक्त प्रकार",
    history: "चिकित्सा इतिहास",
    consultations: "पिछली परामर्श",
    noHistory: "अभी तक कोई परामर्श इतिहास नहीं",
    analyticsTitle: "स्वास्थ्य एनालिटिक्स डैशबोर्ड",
    analyticsSub: "अपने स्वास्थ्य रुझानों और मेट्रिक्स की निगरानी करें",
    heartRate: "हृदय गति",
    bloodPressure: "रक्तचाप",
    sleepHours: "नींद के घंटे",
    stepsToday: "आज के कदम",
    weeklyTrend: "साप्ताहिक स्वास्थ्य रुझान",
    monthlyOverview: "मासिक अवलोकन",
    general: "सामान्य",
    headNeck: "सिर और गर्दन",
    chestLungs: "छाती और फेफड़े",
    abdomen: "पेट",
    musculoskeletal: "मांसपेशी और हड्डी",
    skinHair: "त्वचा और बाल",
    mental: "मानसिक स्वास्थ्य",
    other: "अन्य",
    settings: "सेटिंग्स",
    notifications: "सूचनाएं",
    help: "सहायता",
    logout: "लॉग आउट",
    language: "भाषा",
    theme: "थीम",
    light: "लाइट",
    dark: "डार्क",
    symptomsSaved: "लक्षण आपके स्वास्थ्य इतिहास में सहेजे गए!",
    symptomHistory: "लक्षण इतिहास",
    symptomEntries: "लक्षण प्रविष्टियाँ",
    symptomCheck: "लक्षण जाँच",
  },
};

type Translations = typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("en");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
